"""initial_schema

Revision ID: 7452ffddfa65
Revises: 
Create Date: 2026-06-04 23:01:35.096024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7452ffddfa65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insider_filings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('issuer_name', sa.String(length=255), nullable=True),
    sa.Column('insider_name', sa.String(length=255), nullable=False),
    sa.Column('insider_title', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', 'EXERCISE', name='transactiontype'), nullable=False),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price_per_share', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('is_open_market', sa.Boolean(), nullable=False),
    sa.Column('is_congress', sa.Boolean(), nullable=False),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signal_score', sa.SmallInteger(), nullable=True),
    sa.Column('sec_filing_url', sa.String(length=500), nullable=True),
    sa.Column('sec_accession_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sec_accession_number')
    )
    op.create_index(op.f('ix_insider_filings_filing_date'), 'insider_filings', ['filing_date'], unique=False)
    op.create_index(op.f('ix_insider_filings_is_congress'), 'insider_filings', ['is_congress'], unique=False)
    op.create_index(op.f('ix_insider_filings_signal_score'), 'insider_filings', ['signal_score'], unique=False)
    op.create_index(op.f('ix_insider_filings_symbol'), 'insider_filings', ['symbol'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('benchmark_etf', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_themes_category'), 'themes', ['category'], unique=False)
    op.create_index(op.f('ix_themes_slug'), 'themes', ['slug'], unique=True)
    op.create_table('tickers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_name'), 'tickers', ['name'], unique=False)
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PRO', name='subscriptiontier'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'TRIALING', name='subscriptionstatus'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('theme_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.Enum('ALERT', 'WATCH', 'QUIET', name='convergencelevel'), nullable=False),
    sa.Column('unique_companies_buying', sa.Integer(), nullable=False),
    sa.Column('total_value_accumulated', sa.Float(), nullable=False),
    sa.Column('csuite_count', sa.Integer(), nullable=False),
    sa.Column('congress_signal', sa.Boolean(), nullable=False),
    sa.Column('unusual_options_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_signal', sa.Boolean(), nullable=False),
    sa.Column('signal_breakdown', sa.JSON(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_id')
    )
    op.create_table('theme_tickers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('market_cap_tier', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_id', 'symbol')
    )
    op.create_index(op.f('ix_theme_tickers_symbol'), 'theme_tickers', ['symbol'], unique=False)
    op.create_index(op.f('ix_theme_tickers_theme_id'), 'theme_tickers', ['theme_id'], unique=False)
    op.create_table('user_theme_watchlist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'theme_id')
    )
    op.create_index(op.f('ix_user_theme_watchlist_user_id'), 'user_theme_watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_theme_watchlist_user_id'), table_name='user_theme_watchlist')
    op.drop_table('user_theme_watchlist')
    op.drop_index(op.f('ix_theme_tickers_theme_id'), table_name='theme_tickers')
    op.drop_index(op.f('ix_theme_tickers_symbol'), table_name='theme_tickers')
    op.drop_table('theme_tickers')
    op.drop_table('theme_scores')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_name'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_themes_slug'), table_name='themes')
    op.drop_index(op.f('ix_themes_category'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_insider_filings_symbol'), table_name='insider_filings')
    op.drop_index(op.f('ix_insider_filings_signal_score'), table_name='insider_filings')
    op.drop_index(op.f('ix_insider_filings_is_congress'), table_name='insider_filings')
    op.drop_index(op.f('ix_insider_filings_filing_date'), table_name='insider_filings')
    op.drop_table('insider_filings')
    # ### end Alembic commands ###
